name: Makefile CI

on:
  push:
    branches: [ "vnd_ch6n_h6912-user-12-SP1A.210812.016-295840-release-keys" ]
  pull_request:
    branches: [ "vnd_ch6n_h6912-user-12-SP1A.210812.016-295840-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
